### ISSUE TITLE
Queue federation sets routing key to source queue name

### ISSUE THREAD

**Issue by smee** [rabbitmq/rabbitmq-federation#22]
Queue federation seems to differ in behaviour from exchange federation quite significantly. According to my experiments and the [source](https://github.com/rabbitmq/rabbitmq-federation/blob/master/src/rabbit_federation_queue_link.erl#L149) queue federation changes the routing key to the name of the source queue while exchange federation does not. The documentation does not mention this fact.

Background: I'm evaluating a strategy to update the version of a RMQ-cluster at runtime transparently for users. The logic would be:

0. Let all clients connect to RabbitMQ via a loadbalancer
1. Install cluster with new RMQ version in parallel to the production cluster
2. Copy configuration from old to new cluster (users, permissions, vhosts, exchanges, queues, bindings...)
3. Use queue federation to ensure that users can consume messages independent of the cluster they are connected to. Works like a charm, apart from the changed routing key and added header fields.
4. Reconfigure load balancer to enforce that all new client connection go to the new cluster.
5. Gradually disconnect clients, let them reconnect themselves to the new cluster.

The charm of this usage of queue federation would be that no matter to which cluster a client and a producer are connected to, they can still communicate without being aware of their location.

My question: I would prefer to keep messages transported over queue federation unchanged by the server. Is this possible in any way?

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.

Federation has to move messages between nodes and as long as it does so using "regular" means of client connections and consumers/exchanges/etc, it cannot adapt to route every possible message any other way than via default exchange. `BCC` extension is the only option that may work even in theory.

I'd say relying on the routing key on a message on the consumer end is not a great idea in general. And if you don't do that, the fact that queue federation changes it when a message is re-published shouldn't matter (unless I'm missing something).
