### ISSUE TITLE
[ Rabbit && Federation ]: Federated queues breaking since upgraded to "3.5.1"

### ISSUE THREAD

**Issue by chiriaev** [rabbitmq/rabbitmq-federation#3]
Guys, Hi. I am having the below after I upgraded to the latest Rabbit "3.5.1" and Erlang "17.5". 
...
** Reason for termination ==
** {{shutdown,{server_initiated_close,404,
                                      <<"NOT_FOUND - no exchange '' in vhost '/sensu'">>}},
    {gen_server,call,[<0.14169.4>,next_publish_seqno,infinity]}}
...

Thanks in advance for you feedback.

Regards, Andrei

P.S.: full batch below
...
=ERROR REPORT==== 12-May-2015::15:44:52 ===
Channel error on connection <0.14163.4> (<rabbit@c068amw.2.14163.4>, vhost: '/sensu', user: 'none'), channel 1:
{amqp_error,not_found,"no exchange '' in vhost '/sensu'",'basic.publish'}

=ERROR REPORT==== 12-May-2015::15:44:52 ===
** Generic server <0.14159.4> terminating
** Last message in was {{'basic.deliver',<<"consumer">>,4,false,
                            <<"keepalives">>,<<>>},
                        {amqp_msg,
                            {'P_basic',<<"application/octet-stream">>,
                                undefined,undefined,1,0,undefined,undefined,
                                undefined,undefined,undefined,undefined,
                                undefined,undefined,undefined},
                            <<"{\"name\":\"un2c-cpaadbd01a\",\"address\":\"null\",\"plugin-dir\":\                                                                                     "d:/eikon/monitoring/cfg/sensu/plugins\",\"eikon-environment-class\":\"alpha\",\"region\":\"emea\"                                                                                     ,\"metric-prefix\":\"stats.emea.alpha-dtc-pod.aaa-cpc-adbd.un2c-cpaadbd01a\",\"subscriptions\":[\"                                                                                     os-windows\",\"aaa-cpc-adbd\",\"alpha_aaa-cpc-adbd\"],\"timestamp\":1431445492}">>}}
** When Server state == {state,
                         {amqqueue,
                          {resource,<<"/sensu">>,queue,<<"keepalives">>},
                          false,true,none,[],<0.13204.1>,[],[],[],
                          [{vhost,<<"/sensu">>},
                           {name,<<"federate-head-end-keepalives-queue">>},
                           {pattern,<<"^keepalives$">>},
                           {'apply-to',<<"queues">>},
                           {definition,
                            [{<<"federation-upstream-set">>,<<"head">>}]},
                           {priority,0}],
                          [],
                          [rabbit_federation_queue],
                          live},
                         true,<0.14175.4>,<0.14184.4>,<0.14163.4>,<0.14169.4>,
                         {upstream,
                          [<<"amqp://sensu:sensu@c823bqq.int.mycompany.com/%2Fsensu">>],
                          <<"keepalives">>,<<"keepalives">>,1000,1,1,3600000,
                          none,true,'on-confirm',none,
                          <<"c823bqq.int.mycompany.com">>},
                         {upstream_params,
                          <<"amqp://sensu:sensu@c823bqq.int.mycompany.com/%2Fsensu">>,
                          {amqp_params_network,<<"sensu">>,<<"sensu">>,
                           <<"/sensu">>,"c823bqq.int.mycompany.com",
                           undefined,0,0,0,infinity,none,
                           [#Fun<amqp_uri.9.9354953>,#Fun<amqp_uri.9.9354953>],
                           [],[]},
                          {amqqueue,
                           {resource,<<"/sensu">>,queue,<<"keepalives">>},
                           false,true,none,[],<0.13204.1>,[],[],[],
                           [{vhost,<<"/sensu">>},
                            {name,<<"federate-head-end-keepalives-queue">>},
                            {pattern,<<"^keepalives$">>},
                            {'apply-to',<<"queues">>},
                            {definition,
                             [{<<"federation-upstream-set">>,<<"head">>}]},
                            {priority,0}],
                           [],
                           [rabbit_federation_queue],
                           live},
                          <<"amqp://c823bqq.int.mycompany.com/%2Fsensu">>,
                          [{<<"uri">>,longstr,
                            <<"amqp://c823bqq.int.mycompany.com/%2Fsensu">>},
                           {<<"queue">>,longstr,<<"keepalives">>}]},
                         {3,{1,1,nil,{2,2,nil,{3,3,nil,nil}}}}}
** Reason for termination ==
** {{shutdown,{server_initiated_close,404,
                                      <<"NOT_FOUND - no exchange '' in vhost '/sensu'">>}},
    {gen_server,call,[<0.14169.4>,next_publish_seqno,infinity]}}

=INFO REPORT==== 12-May-2015::15:44:52 ===
Federation queue 'keepalives' in vhost '/sensu' connected to queue 'keepalives' in vhost '/sensu' on amqp://c823bqq.int.mycompany.com/%2Fsensu
...

**Comment by michaelklishin** [comment]
Please use rabbitmq-users for questions. The error says that there is no exchange `""` in vhost `/sensu`. You're not specifying from what version you are upgrading but `3.5.x` [barely had any](http://www.rabbitmq.com/release-notes/README-3.5.0.txt) changes in federation.

**Comment by chiriaev** [comment]
Hi, Michael. Thanks for your prompt reply. I was upgrading from Rabbit "3.3.5" and Erlang "R15B03". 
I am trying older versions in the meantime. (i.e.: and the brand new "3.5.2" ;) )

Regards, Andrei

**Comment by michaelklishin** [comment]
There were no federation changes in 3.5.2, and really not a whole lot in [3.4.x](http://www.rabbitmq.com/changelog.html). Please post more details about your setup to the list. It sounds like a misconfiguration that earlier versions were more lenient about.
