### ISSUE TITLE
Downstream cannot connect using client SSL cert when upstream uses trust store plug-in

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-federation#37]
We have an upstream with trust store plug-in and one cert in the white-list directory. We verified that the cert is loaded by the trust store plug-in. Java client can connect fine using such cert, but the downstream fails with the following message printed in the upstream's log:

`SSL: certify: ssl_handshake.erl:1490:Fatal error: unknown ca`

We do not have 'cacertfile' configured in the upstream. Here is the upstream query string:

`?cacertfile=/tmp/cacert.pem&certfile=/tmp/client.pem&keyfile=/tmp/key.pem&verify=verify_peer&fail_if_no_peer_cert=true&auth_mechanism=external`

This error is also printed when a cert that is used by the client is not loaded into white-list, but in our case it is because Java and Open SSL clients connect just fine. 

When we loaded client cert's CA cert into 'cacertfile' and configured 'cacertfile' with the upstream, the downstream connected fine, but that is not our target setup.

**Comment by michaelklishin** [comment]
Downstream acts as a client and needs to trust upstream's root CA. "Unknown CA" means that no certificate in the presented chain are trusted on the end that produces this TLS alert.
