### ISSUE TITLE
Make it more obvious when a link "gives up" reconnection attempts permanently

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-federation#43]
Currently if a link repeatedly fails to connect upstream (e.g. it cannot authenticate because its user's permissions were revoked), it can eventually stop, which means [its ETS table entry is deleted](https://github.com/rabbitmq/rabbitmq-federation/blob/master/src/rabbit_federation_link_sup.erl#L85).
This can be counter-intuitive, so there are several proposed improvements:

 * Log when a link's supervisor permanently stops
 * Keep a log of such recent events and expose it to federation-management
 * Mark a link in a way that still makes it visible when link status is requested e.g. via federation-management (more intrusive change, not clear where such links can be invalidated/cleared)

**Comment by michaelklishin** [comment]
Note that there is a [code comment](https://github.com/rabbitmq/rabbitmq-federation/blob/master/src/rabbit_federation_link_sup.erl#L80) that covers a relevant scenario and intentionally tries to go an extra mile to not leave extra link records behind. That's also a reasonable
argument.

So this needs to be reconciled with the above somehow. Options 1 and 2 do conflict with it but 3 does.

**Comment by michaelklishin** [comment]
The more I consider various options, the more I am convinced that the non-obvious part is when to clear the records of such "given up" links. If we keep such records around 
the users would have to clean them up. That's something that can be considered a bug, too, so I'm strongly leaning towards improving logging (or even having a separate log of federation link events) instead.

**Comment by uvzubovs** [comment]
Merely logging dropped links is not sufficient for us. If the link disappears, we cannot reliably alert on the link that is not working. Re-creating the link requires access to tools and resources (to re-create the policy) that are ordinarily not available to the operators. We would like to be able to restart the link without re-creating the policy if the plug-in cannot retry forever.

As far as managing dangling links, perhaps you would consider adding "Delete" button to the link status screen and support DELETE verb with api/federation-links. There are times when both upstream and the policy are deleted, but the link remains until the node restarts.

**Comment by michaelklishin** [comment]
@uvzubovs good idea, I filed two issues for `federation-management`.

**Comment by michaelklishin** [comment]
We are no longer sure what else can be improved. Someone is investigating further but this issue is considered close.
