### ISSUE TITLE
Filtering Downstream Federation Messages based on topic/routing key

### ISSUE THREAD

**Issue by elalonde** [rabbitmq/rabbitmq-federation#5]
It would be valuable to provide downstream a mechanism to filter which messages sent to a federated exchange are actually passed to downstream. This would be especially valuable in the context of topic exchanges, where only a subset of the topics on the exchange are interesting to downstream.

Since I cannot see a way to currently achieve this when downstream creates the federation policy, we end up filtering these messages based on the name of the exchange. Those messages that are not interesting to downstream A are sent to a different exchange that might be federated by a different cluster, even though the messages are of the same content. This is certainly feasible, but I find myself wishing for topic-based filtration in the context of federation, especially when we need to separate messages into different federated exchanges based on network topology, since this can get cumbersome as things scale.

I'm requesting that support be added such that when downstream declares its policy, it can additionally express a topic-based (routing key) filtration of federated messages (e.g. statistics.$HOSTNAME.*). The goal here is to avoid putting messages into the queue (and ultimately over the wire) in situations where there does not exist a downstream that has expressed interest in the topic or routing key associated with the message. This  also avoids the unwieldy task of arbitrarily splitting messages onto different exchanges just to avoid sending messages to downstream clusters that are going to drop them on the receiving end.

**Comment by hairyhum** [comment]
Looks like exchange links are working with routing keys (including topic) right now. So when you create query with specific routing key on downstream exchange, upstream will create "federation exchanges" and bind them to upstream exchange for each routing key.
