### ISSUE TITLE
Cleanup internal exchanges and queues after disabling plugin/policy

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-federation#63]
The federation plugins creates internal exchanges, type `x-federation-upstream`, and queues, noted by the argument `federation`:`x-internal-purpose`, to transfer the messages. These internal exchanges and queues are not removed when the the links terminate, either by disabling the plugin or removing the `set-upstream` policy.

The links ensure that both internal resources are present when they are created, thus there is no reason for them to be left behind. Terminating a link should cleanup all these internal resources.

**Comment by michaelklishin** [comment]
#65 backports this to 3.6.x.
