### ISSUE TITLE
Consumer tag with queue federation

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-federation#66]
When federating queues, downstream creates a consumer on the upstream queue with tag "consumer". This seems to be too terse. Would it be possible to name this consumer somewhat more eloquently, e.g. after the downstream? Would consumer tags collide when there is more than one downstream? Thanks

RabbitMQ 3.6.12, Erlang 19.3.6.2

**Comment by hairyhum** [comment]
Consumer tags are scoped by channel, so there should not be any issues with having the same consumer tag on different channels for the same queue.
Technically threre is no such thing as downstream "name", there is only IP, which is already available in the channel info.
But surely a name like "federation-<federation_name>" would be still more representative. Or maybe federated queue settings may include consifurable consumer name field for operators to use.

Sorry for the late reply. We're doing some old story digging.

**Comment by michaelklishin** [comment]
Note that the PRs that add support of user-provided tags are currently set for `3.8.0`.
