### ISSUE TITLE
Exchange federation

### ISSUE THREAD

**Issue by armanpetrosyan23** [rabbitmq/rabbitmq-federation#93]
hi, I have two rabbitMQ cluster  and try to federate Exchange, all hase been successful but second node not receive message, Please help me.
I published message with "demo" routing key and Recaive message that message not routed
This is downstreamNode
![SecondNode](https://user-images.githubusercontent.com/35919382/60187418-9c594080-983e-11e9-9401-ff0299d96f11.PNG)
![Capture1](https://user-images.githubusercontent.com/35919382/60187523-c7439480-983e-11e9-8727-aacc2663f018.PNG)
![Capture3](https://user-images.githubusercontent.com/35919382/60187601-e93d1700-983e-11e9-9e2f-7f2f56916265.PNG)
![656](https://user-images.githubusercontent.com/35919382/60187681-04a82200-983f-11e9-8fff-010de5c42775.PNG)

**Comment by lukebakken** [comment]
Hello,

Thank you for using RabbitMQ. When you click "New Issue", the following text appears. Please read it and ask your question on the mailing list -

----

Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version
* Erlang version
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
A federated exchange replicates messages that are published to it downstream but it has no influence over how messages are routed on the downstream node. If replicated messages do not route anywhere when published by a local client, they would route nowhere when published by the federation plugin.
